server:
  port: 8100

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092

spring.datasource:
  url: jdbc:postgresql://localhost:5432/sistemas_logs
  username: admin
  password: admin
  driver-class-name: org.postgresql.Driver

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update

spring.devtools:
  add-properties: true