server:
  port: 8100

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092
  datasource:
    url: jdbc:postgresql://localhost:5432/sistemas_logs
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    add-properties: true
  log:
    console:
      format: |
        %d{HH:mm:ss} %-5p [%c{2.}] (%t) %X{requestID} %s%e%n

swagger-ui:
  path: /api-docs

main:
  allow-circular-references: true

jwt:
  secret: EEZi3NCjjhshXcjxdJVq7GsKMJ4iJTO2FHTQ3yCMv2w=
  expiration: 1800000
